all:
	$(MAKE) -C CWE-20/src all
	$(MAKE) -C CWE-119/src all
	$(MAKE) -C CWE-120/src all
	$(MAKE) -C CWE-125/src all
	$(MAKE) -C CWE-134/src all
	$(MAKE) -C CWE-170/src all
	$(MAKE) -C CWE-190/src all
	$(MAKE) -C CWE-193/src all
	$(MAKE) -C CWE-195/src all
	$(MAKE) -C CWE-197/src all
#	$(MAKE) -C CWE-222/src all
	$(MAKE) -C CWE-369/src all
	$(MAKE) -C CWE-401/src all
#	$(MAKE) -C CWE-403/src all
	$(MAKE) -C CWE-415/src all
	$(MAKE) -C CWE-416/src all
	$(MAKE) -C CWE-457/src all
	$(MAKE) -C CWE-476/src all
	$(MAKE) -C CWE-665/src all
#	$(MAKE) -C CWE-787/src all
